#!/usr/bin/python

import urllib2
try:
  import simplejson as json
except ImportError:
  import json

def main():

  module = AnsibleModule(
      argument_spec = dict(
        ip = dict(required=False, default="127.0.0.1"),
        port = dict(required=False, default="5050")
      )
  )

  mesos_url = "http://" +  module.params['ip'] + ":" + module.params['port'] + \
              "/stats.json"

  try:
    req = urllib2.Request(mesos_url)
    opener = urllib2.build_opener()
    f = opener.open(req)
  except:
    message="Could not connect to mesos at " + mesos_url
    module.fail_json(msg=message)

  mesos_facts = json.load(f)
  new_facts = {}

  # Need to replace slashes with underscore because I can't
  # seem to use them in {{ some/variable }}
  for key in mesos_facts:
    new_key = str(key).replace("/", "_")
    new_facts[new_key] = mesos_facts[key]

  # Create a top level mesos dict so that vars can be accessed with
  # mesos.somevar instead of just somevar
  mesos_dict = {"mesos": new_facts }
  module.exit_json(changed=False, ansible_facts=mesos_dict)


from ansible.module_utils.basic import *
main()
